/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vending_Machine;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Neelima Rambabu
 */
public class Vending_machine extends javax.swing.JFrame {

    /**
     * Creates new form Vending_machine
     */
    public Vending_machine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        drink = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        sprite = new javax.swing.JRadioButton();
        pepsi = new javax.swing.JRadioButton();
        coke = new javax.swing.JRadioButton();
        limca = new javax.swing.JRadioButton();
        coffee = new javax.swing.JRadioButton();
        tea = new javax.swing.JRadioButton();
        fanta = new javax.swing.JRadioButton();
        mirinda = new javax.swing.JRadioButton();
        thumbsup = new javax.swing.JRadioButton();
        clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        noi = new javax.swing.JTextField();
        cost = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        amounten1 = new javax.swing.JLabel();
        entamt = new javax.swing.JTextField();
        amounten = new javax.swing.JLabel();
        change = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        buy = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        calculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        title.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        title.setForeground(new java.awt.Color(51, 51, 0));
        title.setText("Cool Drink Vending Machine");

        drink.setBackground(new java.awt.Color(255, 255, 255));
        drink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        drink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vending_Machine/cvm1.jpg"))); // NOI18N
        drink.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        sprite.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        sprite.setForeground(new java.awt.Color(0, 204, 0));
        sprite.setText("Sprite Rs.25");
        sprite.setToolTipText("");
        sprite.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                spriteComponentAdded(evt);
            }
        });
        sprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriteActionPerformed(evt);
            }
        });

        pepsi.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        pepsi.setForeground(new java.awt.Color(10, 10, 191));
        pepsi.setText("Pepsi Rs.30");
        pepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepsiActionPerformed(evt);
            }
        });

        coke.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        coke.setForeground(new java.awt.Color(204, 0, 0));
        coke.setText("Coke Rs.30");
        coke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokeActionPerformed(evt);
            }
        });

        limca.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        limca.setForeground(new java.awt.Color(51, 51, 51));
        limca.setText("Limca Rs.28");
        limca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limcaActionPerformed(evt);
            }
        });

        coffee.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        coffee.setForeground(new java.awt.Color(102, 51, 0));
        coffee.setText("CoffeeRs.15");
        coffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coffeeActionPerformed(evt);
            }
        });

        tea.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        tea.setForeground(new java.awt.Color(153, 102, 0));
        tea.setText("Tea Rs.15");
        tea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaActionPerformed(evt);
            }
        });

        fanta.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        fanta.setForeground(new java.awt.Color(255, 51, 0));
        fanta.setText("Fanta Rs.28");
        fanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fantaActionPerformed(evt);
            }
        });

        mirinda.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        mirinda.setForeground(new java.awt.Color(255, 102, 0));
        mirinda.setText("Mirinda Rs.29");
        mirinda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mirindaActionPerformed(evt);
            }
        });

        thumbsup.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        thumbsup.setForeground(new java.awt.Color(0, 0, 102));
        thumbsup.setText("ThumbsUp Rs.29");
        thumbsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thumbsupActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(153, 153, 153));
        clear.setFont(new java.awt.Font("Sylfaen", 3, 14)); // NOI18N
        clear.setText("CLEAR");
        clear.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("No of items:");

        noi.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        noi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        noi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cost.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        cost.setForeground(new java.awt.Color(51, 0, 0));
        cost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cost.setText("Total cost");

        amount.setEditable(false);
        amount.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        amount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        amounten1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        amounten1.setForeground(new java.awt.Color(51, 0, 0));
        amounten1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amounten1.setText("Eneter Amount");

        entamt.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        entamt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entamt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        amounten.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        amounten.setForeground(new java.awt.Color(51, 0, 0));
        amounten.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amounten.setText("Change");

        change.setEditable(false);
        change.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        change.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        change.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select Your Drink");

        buy.setBackground(new java.awt.Color(153, 153, 153));
        buy.setFont(new java.awt.Font("Sylfaen", 3, 14)); // NOI18N
        buy.setText("BUY");
        buy.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buy.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                buyAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(102, 102, 102));
        exit.setFont(new java.awt.Font("Sylfaen", 3, 14)); // NOI18N
        exit.setText("EXIT");
        exit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        calculate.setBackground(new java.awt.Color(0, 153, 0));
        calculate.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        calculate.setText("Calculate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sprite, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(limca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fanta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(amounten1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(amounten, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(buy, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(change)
                                    .addComponent(entamt, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(mirinda)
                                        .addComponent(thumbsup, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(pepsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(34, 34, 34))
                                        .addComponent(noi)
                                        .addComponent(amount)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(coke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(coffee, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(176, 176, 176))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sprite)
                    .addComponent(pepsi)
                    .addComponent(coke))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limca)
                    .addComponent(tea)
                    .addComponent(mirinda))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fanta)
                    .addComponent(coffee)
                    .addComponent(thumbsup))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(noi, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amounten1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entamt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amounten, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buy, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drink, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drink))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        buy.setEnabled(false);
        noi.setEnabled(false);
        entamt.setEnabled(false);
        calculate.setEnabled(false);
         
        
    }//GEN-LAST:event_formWindowActivated

    private void teaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaActionPerformed
        // TODO add your handling code here:
         if(tea.isSelected())
        { noi.setText("");
            entamt.setText("");
            amount.setText("");
            change.setText("");
            calculate.setEnabled(true);
            noi.setEnabled(true);
            entamt.setEnabled(true);
            sprite.setSelected(false);
            pepsi.setSelected(false);
            coke.setSelected(false);
             mirinda.setSelected(false);
             fanta.setSelected(false);
             coffee.setSelected(false);
             limca.setSelected(false);
             thumbsup.setSelected(false);
             drink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vending_Machine/tea.jpg"))); 
        }
    }//GEN-LAST:event_teaActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
             sprite.setSelected(false);
             pepsi.setSelected(false);
             limca.setSelected(false);
             coke.setSelected(false);
             mirinda.setSelected(false);
             fanta.setSelected(false);
             coffee.setSelected(false);
             tea.setSelected(false);
             thumbsup.setSelected(false);
             noi.setText("");
             entamt.setText("");
             change.setText("");
             amount.setText("");
             drink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vending_Machine/cvm1.jpg"))); 
    }//GEN-LAST:event_clearActionPerformed
private JFrame frame;
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
         frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Cool Drink Vending Machine",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
        {
           System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed
    
    private void spriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriteActionPerformed
        // TODO add your handling code here:
        if(sprite.isSelected())
        {
            noi.setText("");
            entamt.setText("");
            amount.setText("");
            change.setText("");
             noi.setEnabled(true);
          entamt.setEnabled(true);
          
             pepsi.setSelected(false);
             limca.setSelected(false);
             coke.setSelected(false);
             mirinda.setSelected(false);
             fanta.setSelected(false);
             coffee.setSelected(false);
             tea.setSelected(false);
             thumbsup.setSelected(false);
             drink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vending_Machine/sprite.jpg")));
             calculate.setEnabled(true);
        }
    }//GEN-LAST:event_spriteActionPerformed

    private void pepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepsiActionPerformed
        // TODO add your handling code here:
                   if(pepsi.isSelected())
                   { 
                       noi.setText("");
            entamt.setText("");
            amount.setText("");
            change.setText("");
                        noi.setEnabled(true);
          entamt.setEnabled(true);
          
                       calculate.setEnabled(true);
                    sprite.setSelected(false);
                    limca.setSelected(false);
                    coke.setSelected(false);
                    mirinda.setSelected(false);
                    fanta.setSelected(false);
                    coffee.setSelected(false);
                    tea.setSelected(false);
                    thumbsup.setSelected(false);
                    drink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vending_Machine/pepsi3.jpg"))); 
                   }
    }//GEN-LAST:event_pepsiActionPerformed

    private void cokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cokeActionPerformed
        // TODO add your handling code here:
        if(coke.isSelected())
        { 
            noi.setText("");
            entamt.setText("");
            amount.setText("");
            change.setText("");
            calculate.setEnabled(true);
            sprite.setSelected(false);
             pepsi.setSelected(false);
             limca.setSelected(false);
             mirinda.setSelected(false);
             fanta.setSelected(false);
             coffee.setSelected(false);
             tea.setSelected(false);
             thumbsup.setSelected(false);
               drink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vending_Machine/coke.jpg"))); 
        }
    }//GEN-LAST:event_cokeActionPerformed

    private void limcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limcaActionPerformed
        // TODO add your handling code here:
          if(limca.isSelected())
        {
            noi.setText("");
            entamt.setText("");
            amount.setText("");
            change.setText("");
             noi.setEnabled(true);
          entamt.setEnabled(true);
          
            calculate.setEnabled(true);
            sprite.setSelected(false);
             pepsi.setSelected(false);
              coke.setSelected(false);
             mirinda.setSelected(false);
             fanta.setSelected(false);
             coffee.setSelected(false);
             tea.setSelected(false);
             thumbsup.setSelected(false);
               drink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vending_Machine/limca.jpg"))); 
        }
    }//GEN-LAST:event_limcaActionPerformed

    private void mirindaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mirindaActionPerformed
        // TODO add your handling code here:
         if(mirinda.isSelected())
        {
            noi.setText("");
            entamt.setText("");
            amount.setText("");
            change.setText("");
            calculate.setEnabled(true);
            sprite.setSelected(false);
             pepsi.setSelected(false);
              coke.setSelected(false);
             limca.setSelected(false);
             fanta.setSelected(false);
             coffee.setSelected(false);
             tea.setSelected(false);
             thumbsup.setSelected(false);
             drink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vending_Machine/mirinda.jpg"))); 
        }
    }//GEN-LAST:event_mirindaActionPerformed

    private void fantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fantaActionPerformed
        // TODO add your handling code here:
         if(fanta.isSelected())
        {
            noi.setText("");
            entamt.setText("");
            amount.setText("");
            change.setText("");
             noi.setEnabled(true);
          entamt.setEnabled(true);
          
            calculate.setEnabled(true);
            sprite.setSelected(false);
             pepsi.setSelected(false);
              coke.setSelected(false);
             mirinda.setSelected(false);
             limca.setSelected(false);
             coffee.setSelected(false);
             tea.setSelected(false);
             thumbsup.setSelected(false);
             drink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vending_Machine/fanta.jpg"))); 
        }

    }//GEN-LAST:event_fantaActionPerformed

    private void thumbsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thumbsupActionPerformed
        // TODO add your handling code here:
         if(thumbsup.isSelected())
        {
            noi.setText("");
            entamt.setText("");
            amount.setText("");
            change.setText("");
             noi.setEnabled(true);
          entamt.setEnabled(true);
          
            calculate.setEnabled(true);
            sprite.setSelected(false);
             pepsi.setSelected(false);
              coke.setSelected(false);
             mirinda.setSelected(false);
             fanta.setSelected(false);
             coffee.setSelected(false);
             tea.setSelected(false);
             limca.setSelected(false);
             drink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vending_Machine/thumsup.jpg"))); 
        }
    }//GEN-LAST:event_thumbsupActionPerformed

    private void coffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coffeeActionPerformed
        // TODO add your handling code here:
         if(coffee.isSelected())
        {
            noi.setText("");
            entamt.setText("");
            amount.setText("");
            change.setText("");
             noi.setEnabled(true);
          entamt.setEnabled(true);
          
            calculate.setEnabled(true);
            sprite.setSelected(false);
             pepsi.setSelected(false);
              coke.setSelected(false);
             mirinda.setSelected(false);
             fanta.setSelected(false);
             limca.setSelected(false);
             tea.setSelected(false);
             thumbsup.setSelected(false);
             drink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vending_Machine/coffee1.jpg"))); 
             
        }
    }//GEN-LAST:event_coffeeActionPerformed

    private void spriteComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_spriteComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_spriteComponentAdded

    private void buyAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_buyAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_buyAncestorAdded
   
    private void buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyActionPerformed
        // TODO add your handling code here:
        
        Integer nois = Integer.parseInt(noi.getText());
        
        if(sprite.isSelected())
        {
            int cost = nois*25;
            amount.setText("Rs. "+cost+".00");
            Integer paid = Integer.parseInt(entamt.getText());
            int pay = paid-cost;
            if(pay<0)
            {
                change.setText("");
                frame = new JFrame("Payment ");
                    if(JOptionPane.showConfirmDialog(frame,"Insufficient Amount\nDo You wnat to exit?","Cool Drink Vending Machine",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
                    {
                       System.exit(0);
                    }
            }
            else
            {
                    
              change.setText("Rs. "+pay+".00");
            }
        }
        
        else if(pepsi.isSelected())
        {
            int cost = nois*30;
            amount.setText("Rs. "+cost+".00");
            Integer paid = Integer.parseInt(entamt.getText());
            int pay = paid-cost;
            if(pay<0)
            { change.setText("");
                frame = new JFrame("Payment ");
                    if(JOptionPane.showConfirmDialog(frame,"Insufficient Amount\nDo You wnat to exit?","Cool Drink Vending Machine",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
                    {
                       System.exit(0);
                    }
            }
            else
            {
                    
                change.setText("Rs. "+pay+".00");
            }
        }
        else if(coke.isSelected())
        { 
            change.setText("");
            int cost = nois*30;
            amount.setText("Rs. "+cost+".00");
            Integer paid = Integer.parseInt(entamt.getText());
            int pay = paid-cost;
            if(pay<0)
            {
                frame = new JFrame("Payment ");
                    if(JOptionPane.showConfirmDialog(frame,"Insufficient Amount\nDo You wnat to exit?","Cool Drink Vending Machine",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
                    {
                       System.exit(0);
                    }
            }
            else
            {
               change.setText("Rs. "+pay+".00");
            }
        }else if(limca.isSelected())
        { 
            change.setText("");
            int cost = nois*28;
            amount.setText("Rs. "+cost+".00");
            Integer paid = Integer.parseInt(entamt.getText());
            int pay = paid-cost;
            if(pay<0)
            {
                frame = new JFrame("Payment ");
                    if(JOptionPane.showConfirmDialog(frame,"Insufficient Amount\nDo You wnat to exit?","Cool Drink Vending Machine",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
                    {
                       System.exit(0);
                    }
            }
            else
            {
               change.setText("Rs. "+pay+".00");   
            }
        }
        else if(mirinda.isSelected())
        {
            change.setText("");
            int cost = nois*29;
            amount.setText("Rs. "+cost+".00");
            Integer paid = Integer.parseInt(entamt.getText());
            int pay = paid-cost;
            if(pay<0)
            {
                frame = new JFrame("Payment ");
                    if(JOptionPane.showConfirmDialog(frame,"Insufficient Amount\nDo You wnat to exit?","Cool Drink Vending Machine",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
                    {
                       System.exit(0);
                    }
            }
            else
            {
                    
                change.setText("Rs. "+pay+".00");
            }
        }
        else if(fanta.isSelected())
        {
            change.setText("");
            int cost = nois*28;
            amount.setText("Rs. "+cost+".00");
            Integer paid = Integer.parseInt(entamt.getText());
            int pay = paid-cost;
            if(pay<0)
            {
                frame = new JFrame("Payment ");
                    if(JOptionPane.showConfirmDialog(frame,"Insufficient Amount\nDo You wnat to exit?","Cool Drink Vending Machine",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
                    {
                       System.exit(0);
                    }
            }
            else
            {
               change.setText("Rs. "+pay+".00");
            }
        }
        else if(thumbsup.isSelected())
        {
            change.setText("");
            int cost = nois*29;
            amount.setText("Rs. "+cost+".00");
            Integer paid = Integer.parseInt(entamt.getText());
            int pay = paid-cost;
            if(pay<0)
            {
                frame = new JFrame("Payment ");
                    if(JOptionPane.showConfirmDialog(frame,"Insufficient Amount\nDo You wnat to exit?","Cool Drink Vending Machine",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
                    {
                       System.exit(0);
                    }
            }
            else
            {
                    
                change.setText("Rs. "+pay+".00");
            }
        }
        else if(coffee.isSelected())
        {
            change.setText("");
            int cost = nois*15;
            amount.setText("Rs. "+cost+".00");
            Integer paid = Integer.parseInt(entamt.getText());
            int pay = paid-cost;
            if(pay<0)
            {
                frame = new JFrame("Payment ");
                    if(JOptionPane.showConfirmDialog(frame,"Insufficient Amount\nDo You wnat to exit?","Cool Drink Vending Machine",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
                    {
                       System.exit(0);
                    }
            }
            else
            {
                    
               change.setText("Rs. "+pay+".00");
            }
        }
        else if(tea.isSelected())
        {
            change.setText("");
            int cost = nois*15;
            amount.setText("Rs. "+cost+".00");
            Integer paid = Integer.parseInt(entamt.getText());
            int pay = paid-cost;
            if(pay<0)
            {
                frame = new JFrame("Payment ");
                    if(JOptionPane.showConfirmDialog(frame,"Insufficient Amount\nDo You wnat to exit?","Cool Drink Vending Machine",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
                    {
                       System.exit(0);
                    }
            }
            else
            {
                    
                change.setText("Rs. "+pay+".00");
            }
        }
        
        
        
        
        
        
         
    }//GEN-LAST:event_buyActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        Integer nois = Integer.parseInt(noi.getText());
        if((sprite.isSelected())&&(nois>0))
        {
            int cost;
            cost = nois*25;
            amount.setText("Rs. "+cost+".00");
            buy.setEnabled(true);
        }
        else if((pepsi.isSelected())&&(nois>0))
        {   
             int cost;
            cost = nois*30;
            amount.setText("Rs. "+cost+".00");
            buy.setEnabled(true);
        }
        else if((limca.isSelected())&&(nois>0))
        {
             int cost;
            cost = nois*28;
            amount.setText("Rs. "+cost+".00");
            buy.setEnabled(true);
        }
        else if((mirinda.isSelected())&&(nois>0))
        {
             int cost;
            cost = nois*29;
            amount.setText("Rs. "+cost);
            buy.setEnabled(true);
        }
        else if((fanta.isSelected())&&(nois>0))
        {
             int cost;
            cost = nois*28;
            amount.setText("Rs. "+cost+".00");
            buy.setEnabled(true);
        }
        else if((thumbsup.isSelected())&&(nois>0))
        {
             int cost;
            cost = nois*29;
            amount.setText("Rs. "+cost+".00");
            buy.setEnabled(true);
        }
        else if((coffee.isSelected())&&(nois>0))
        {
             int cost;
            cost = nois*15;
            amount.setText("Rs. "+cost+".00");
            buy.setEnabled(true);
        }
        else if((tea.isSelected())&&(nois>0))
        {
             int cost;
            cost = nois*15;
            amount.setText("Rs. "+cost+".00");
            buy.setEnabled(true);
        }
        else if((coke.isSelected())&&(nois>0))
        {
             int cost;
            cost = nois*30;
            amount.setText("Rs. "+cost+".00");
            buy.setEnabled(true);
        }
    }//GEN-LAST:event_calculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vending_machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vending_machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vending_machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vending_machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vending_machine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JLabel amounten;
    private javax.swing.JLabel amounten1;
    private javax.swing.JButton buy;
    private javax.swing.JButton calculate;
    private javax.swing.JTextField change;
    private javax.swing.JButton clear;
    private javax.swing.JRadioButton coffee;
    private javax.swing.JRadioButton coke;
    private javax.swing.JLabel cost;
    private javax.swing.JLabel drink;
    private javax.swing.JTextField entamt;
    private javax.swing.JButton exit;
    private javax.swing.JRadioButton fanta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton limca;
    private javax.swing.JRadioButton mirinda;
    private javax.swing.JTextField noi;
    private javax.swing.JRadioButton pepsi;
    private javax.swing.JRadioButton sprite;
    private javax.swing.JRadioButton tea;
    private javax.swing.JRadioButton thumbsup;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
